# Namespace
apiVersion: v1
kind: Namespace
metadata:
   name: dev

---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: python-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: sjortiz/python-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 8080

---

# service (svc)
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: python-app
  type: LoadBalancer
